spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exercise
    username: postgres
    password: postgres
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp